### PR TITLE
Added Filterable Bus Schedule

### PR DESCRIPTION
**Pull request by olafwrieden**
This pull request replaces @ChenhuiLyu1's 2200+ line bus schedule viewer with a 160 line solution. @ChenhuiLyu1 @theamiguel it may be helpful if you look over this and understand how it renders each row.

@hamishmaritz I simply over-wrote Chen's code and didn't make any other changes, if you remove the site-wrapper and push this component into the home page (together with the QR code stuff) rather than having an additional page for this, that would be cool.

**In this pull request:**

- An API call to `GET /trips` route is made and a list of trips saved to state.
- A generic default message will be displayed if an error occurred while querying the endpoint.
- From the response, routes are extracted and fed to a dropdown for selection.
- Based on the selected route, trips are conditionally rendered into a table.
- An `onClick()` handler for each route produces an alert with trip information.

**Future improvements:**

- Current time checking is done with string comparisons, not Dates.
- Add info message if no more buses on this route are running past this time.

### CODE REVIEW

**Comment by hamishM94** [comment]
Added Thea and Chen to review over to understand how it works

**Comment by olafwrieden** [comment]
@mikegjeff Take a look at some of the improvements I made to your scan-on function. @hamishmaritz I think you can go ahead and approve it before it becomes out-dated. Chen took a look at this last night to clarify what some parts were doing and I don't think he's adding anything else.

**Review by mikegjeff — COMMENTED** [review]
Is great, awesome polish and functionality

**Review by hamishM94 — APPROVED** [review]
Looks good

**Pull request merged**
