### PR TITLE
Admin Dashboard

### PR DESCRIPTION
**Pull request by hamishM94**
Implemented some graphs and the nav link is only accessed if user role is 1 so log in as an admin. need to implement a privateroute wrapper around it but tired right now to write it so if you want to feel free otherwise ill do it tomorrow if i get a chance. 

im not even sorry for the formatting

### CODE REVIEW

**Comment by hamishM94** [comment]
i fixed the merge conflict, check it so it doesnt fudge everything up thank u

**Comment by mikegjeff** [comment]
Yo its not even running a little bit lol.

I had to fix the package.json because that was missing a commma, and now the homepage wont even load because fuck know why, several errors.

@hamishmaritz

**Comment by mikegjeff** [comment]
the admindash file is nice, you cant merge it though haha

**Comment by hamishM94** [comment]
closing and resubmitting

**Pull request closed without merging**
