### PR TITLE
All links functional, DB calls working and populating entries

### PR DESCRIPTION
**Pull request by mikegjeff**
Everything is working, enough for a pretty video demonstration. Needs so type of top up implementation. Changed the formatting on Thea and Chens code, and changes a few other things too.

### CODE REVIEW

**Comment by olafwrieden** [comment]
@mikegjeff @ChenhuiLyu1 Just ran this branch. It causes an infinite loop when attempting to load the homepage without having logged in (a token present).

**Comment by mikegjeff** [comment]
@olafwrieden good to go now, check messenger/change log. My fix is still kinda gash, but I don't think its worth doing it properly until the next sprint because I'm going to have to change all of the state management stuff anyway.

**Comment by mikegjeff** [comment]
@olafwrieden edit profile needs quite a bit of work. It's functional but it wont work if any of the 4 entries are the same (all 4 need to be different), whether that needs changing at the API level, or through validation in redux I am unsure. @ChenhuiLyu1

**Review by olafwrieden — APPROVED** [review]
Approved, but consider adding a gender dropdown at registration, rather than assuming every user is male. Also small things like ensuring a user can't get to login/register when they are already logged in. Maybe @hamishmaritz will overhaul it to tighten it all up.

**Pull request merged**
