### PR TITLE
Payment changes

### PR DESCRIPTION
**Pull request by mikegjeff**
**Payment Page**
Removed redundant buttons for features we didn't implement
Made it obvious what to click
Added dynamic drop down
Added conditional rendering of the paypal button

**Registration Page**
Added checks for API being down
Correctly implemented isSubmitting (grey out the submit button - wasn't working earlier)
Added checks for API presence
Added checks for duplicate email based on API feedback

### CODE REVIEW

**Comment by mikegjeff** [comment]
i broke it

**Comment by mikegjeff** [comment]
@olafwrieden Have a look now, did something clever, its all working. Conditional rendering of the Paypal button based on the amount selected too :) I'm kinda proud of myself so I hope it works for you!!!

**Comment by mikegjeff** [comment]
line 102 could maybe be done better? I couldn't find away to get the onClick to accept a the variable from the array, it was just taking the last one every time because asynchronous, what I did works, but could be bad practice, I'm not sure, let me know :)

**Comment by mikegjeff** [comment]
And if you could work out a way to make the drop down menu hide after you click i'd be happier too. Tabler docs are down so i can't see how they did it, and none of the bootstrap methods are working that I can see.

**Comment by olafwrieden** [comment]
@mikegjeff I think you forgot to push the code upstream.

**Comment by mikegjeff** [comment]
HAHAHA I did, Im Thea now ;)

**Comment by olafwrieden** [comment]
What does the `handleChange()` function do? It's never called.

**Comment by mikegjeff** [comment]
legacy code I think. It was taken from a tutorial when I created the page during sprint1.

Its just used by the old form tutorial I first used to update state when the form changes. Was never required, but I was probably to scared to remove it during sprint 1 because I didn't know what it did... ha ha

**Comment by mikegjeff** [comment]
@olafwrieden ready now. I also made some changes to the registration error handling which I forgot about, and merged them to save having to do a second PR.

**Review by olafwrieden — APPROVED** [review]
Errors resolved, pass-by-reference (state) replaced by more robust pass-by-value. In this case, the PayPal window pop-up seemed to clear state, hence the selected amount was unavailable by the time it reached the success method `topUp()`. Ready for you to merge.

**Pull request merged**
