### PR TITLE
Closing Account

### PR DESCRIPTION
**Pull request by olafwrieden**
PR'd this for @ChenhuiLyu1. Review and point out anything that needs to be changed so he can fix it.

Side-note: I have added a soft-delete function to the backend so that data will not be removed from the table(s) permanently, rather a `deleted_At` column registers the time when a user is deleted - therefore don't expect the entire row to disappear.

### CODE REVIEW

**Comment by hamishM94** [comment]
Will test and review this in the morning tomorrow. Thanks @olafwrieden

**Comment by hamishM94** [comment]
1. Issues surrounding the closing of account not working correctly when testing. Have sent through an image via messenger to you @ChenhuiLyu1 
2. Seems that the top right corner user details reverts back to the wrapper using 'Hamish Maritz' rather than the user logged in. e.g. 'Test Tester' should appear but instead 'Hamish Maritz' appears from the wrapper.

**Comment by olafwrieden** [comment]
Relates to the API PR 'Added Soft-Delete', it someone could approve it.

**Comment by hamishM94** [comment]
> Relates to the API PR 'Added Soft-Delete', it someone could approve it.

have approved it, will test again shortly

**Comment by hamishM94** [comment]
@ChenhuiLyu1 Please have a check to see if you can fix the second issue i listed above

**Comment by olafwrieden** [comment]
I pushed an update to the site-wrapper this afternoon, be sure to pull the latest changes. I touched the Account Dropdown but not specifically in relation to this issue.

**Comment by ChenhuiLyu1** [comment]
@hamishmaritz  The second issue has been fixed, Please check it.

**Comment by olafwrieden** [comment]
@hamishmaritz See the last comment. Check and move to done on Trello if it works as expected.

**Comment by hamishM94** [comment]
@ChenhuiLyu1  Looking at the files changed it needs to be set to state rather than 'AUT Shuttle User'

**Comment by hamishM94** [comment]
The PR is has been out for 9 days now. Might be worth declining and then pulling from master and re-submitting. @olafwrieden thoughts?

**Comment by olafwrieden** [comment]
> The PR is has been out for 9 days now. Might be worth declining and then pulling from master and re-submitting. @olafwrieden thoughts?

Agree. I lost track of what the problem is/was. Would you be able to re-PR his branch with the latest changes @hamishmaritz

**Comment by hamishM94** [comment]
@olafwrieden Yep, no worries.

**Comment by hamishM94** [comment]
Declined

**Pull request closed without merging**
