### PR TITLE
Implementation of PWA 

### PR DESCRIPTION
**Pull request by hamishM94**
PWA Implementation and Service Worker Running

pwa_1
serviceworker

### CODE REVIEW

**Comment by hamishM94** [comment]
HTTPS Traffic will always show a warning icon as its served over localhost rather than deployed

**Comment by olafwrieden** [comment]
Nice! I see the service worker registering. Is there an offline component to this where the user, once they are logged in. Can at least access their QR code/dashboard without an internet connection? The reason for going PWA.

**Comment by hamishM94** [comment]
@olafwrieden Yeah, i have that mainly set up just waiting on confirmation from @mikegjeff  that the QR code is up and running ok so that i can finish implementing, commit then push

**Comment by olafwrieden** [comment]
Ok. I will approve this for now.
But will add to the Trello card based on the feedback and sprint 2 goals.

**Review by olafwrieden — APPROVED** [review]

**Pull request merged**
